### ISSUE TITLE
App crashes on start due to NoClassDefFoundError

### ISSUE THREAD

**Issue by pwillmann** [pandulapeter/beagle#54]
Version: `2.0.0-beta19` (same with beta18)

I added the `ui-drawer` version of the library and call `Beagle.initialize(this)` in the onCreate block of my application, which leads to the app crashing with the following exception: 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pandulapeter/beagle/common/contracts/BeagleContract$DefaultImpls;
```

I added the following dependencies: 
```
    debugImplementation("com.github.pandulapeter.beagle:ui-drawer:2.0.0-beta19")
    releaseImplementation("com.github.pandulapeter.beagle:noop:2.0.0-beta19")
```

**Comment by pandulapeter** [comment]
Hi,

Thanks for the bug report. I'm pretty sure that this is because your project's Kotlin version is smaller than 1.4. Can you confirm that?

If upgrading to Kotlin 1.4 is not yet an option for you, Beagle 2.0.0-beta14 should work fine.

**Comment by pandulapeter** [comment]
...or are you already on Kotlin 1.4.10? I haven't tested it yet but it might be an issue, if that's the case let me know and I'll quickly release a new version.

**Comment by pwillmann** [comment]
Ahh I'm using Kotlin `1.3.72` right now, will try with `1.4.0` and let you know if it works. 

Thanks for the quick reply!!

**Comment by pwillmann** [comment]
It's working with Kotlin 1.4 ! Thanks for your help :)

**Comment by pandulapeter** [comment]
You're welcome, let me know if you find anything else :) If you feel like going for 1.4.10, bump the Beagle version to [2.0.0-beta20](https://github.com/pandulapeter/beagle/releases/tag/2.0.0-beta20), it should be available in a few minutes.
